export const API_KEY = import.meta.env.VITE_OMDB_API_KEY ?? '271d25e3';
export const FALLBACK_API_KEY = 'thewdb';
export const API_BASE_URL = import.meta.env.VITE_OMDB_API_BASE_URL ?? 'https://www.omdbapi.com/';
export const FAVORITES_STORAGE_KEY = 'movieApp_favorites';
export const SEARCH_HISTORY_KEY = 'movieApp_searchHistory';
export const AUTH_USER_KEY = 'movieApp_currentUser';
export const ACCOUNTS_STORAGE_KEY = 'movieApp_accounts';
export const DEBOUNCE_DELAY = 500;
export const MAX_SEARCH_HISTORY = 10;
export const DEFAULT_HOME_QUERY = 'movie';
export const DEFAULT_POSTER = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="300" height="450" viewBox="0 0 300 450"%3E%3Crect fill="%23374151" width="300" height="450"/%3E%3Ctext fill="%239CA3AF" font-family="sans-serif" font-size="30" dy="10.5" font-weight="bold" x="50%25" y="50%25" text-anchor="middle"%3ENo Poster%3C/text%3E%3C/svg%3E';
